name: Mirror GitHub to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync GitHub to GitLab
        uses: eskopp/github-to-gitlab@v1
        with:
          git_username: "ZXNrb3Bw"
          git_email: "c2tvcHAuZXJpa0BnbWFpbC5jb20="
          gitlab_repo: "aHR0cHM6Ly9jbG91ZC5lcmlrLXNrb3BwLmRlL3JlbW90ZS5waHAvZGF2L2ZpbGVzL0VyaWsvU291cmNlQ29kZS9HaXRIdWIvQWR2ZW50b2ZDaGVzcw=="
          gitlab_token: ${{ secrets.GITLAB }}
          github_token: ${{ secrets.GH_TOKEN }}
          base64: "true"