name: Deploy Erik Website

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 1 * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set current date
        run: echo "DATETIME=$(date +'%Y_%m_%d_%H_%M')" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install Hugo Extended
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Build Hugo site
        run: |
          hugo mod get
          hugo mod tidy
          hugo

      - name: Deploy files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          source: "public/*"
          target: "/var/www/adventofchess"
          rm: true
          password: ${{ secrets.SSH_PASSWORD }}

      - name: Create folder structure
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/adventofchess
            mv public/* .
            rm -rf public
